/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConsultaRouteImport } from './routes/consulta'
import { Route as AmostrasRouteImport } from './routes/amostras'
import { Route as IndexRouteImport } from './routes/index'

const ConsultaRoute = ConsultaRouteImport.update({
  id: '/consulta',
  path: '/consulta',
  getParentRoute: () => rootRouteImport,
} as any)
const AmostrasRoute = AmostrasRouteImport.update({
  id: '/amostras',
  path: '/amostras',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/amostras': typeof AmostrasRoute
  '/consulta': typeof ConsultaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/amostras': typeof AmostrasRoute
  '/consulta': typeof ConsultaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/amostras': typeof AmostrasRoute
  '/consulta': typeof ConsultaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/amostras' | '/consulta'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/amostras' | '/consulta'
  id: '__root__' | '/' | '/amostras' | '/consulta'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmostrasRoute: typeof AmostrasRoute
  ConsultaRoute: typeof ConsultaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/consulta': {
      id: '/consulta'
      path: '/consulta'
      fullPath: '/consulta'
      preLoaderRoute: typeof ConsultaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amostras': {
      id: '/amostras'
      path: '/amostras'
      fullPath: '/amostras'
      preLoaderRoute: typeof AmostrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmostrasRoute: AmostrasRoute,
  ConsultaRoute: ConsultaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
